[package]
name = "geojson_vt"
version = "0.1.0"
edition = "2024"

[dependencies]
geojson = "0.24.2"
serde_json = { version = "1", features = ["float_roundtrip"] }
[dev-dependencies]
criterion = "0.5.1"
approx = "0.5.1"
